### ISSUE TITLE
Update needed

### ISSUE THREAD

**Issue by BellemareMederic** [rsrdesarrollo/DigistumpArduino#1]
Hello there i have try your compiled Micronucleus but i have the

Warning: device with unknown new version of Micronucleus detected.
This tool doesn't know how to upload to this new device. Updates may be available.
Device reports version as: 2.2

classic error its possible to compile your code with the recent version of micronucleus ? if you know how can you explain

**Comment by ArminJo** [comment]
Please try the new [version 1.6.8](https://github.com/ArminJo/DigistumpArduino) of Digistump avr core.
The Keyboard mod is included.
