### ISSUE TITLE
Fix some special chars/symbols in LAYOUT_PORTUGUESE_BRAZILIAN

### ISSUE THREAD

**Issue by alecgn** [rsrdesarrollo/DigistumpArduino#2]
The following code:

```
DigiKeyboard.println("abcçdefghijklmnopqrstuvwxyz");
DigiKeyboard.println("ABCÇDEFGHIJKLMNOPQRSTUVWXYZ");
DigiKeyboard.println("0123456789/*-+,");
DigiKeyboard.println("\"'!@#$%¨&*()_-+=|\\`´{[^~}]<,>.:;?/");
```

is actualliy producing this output:

```
ABCASDEFGHIJKLMNOPQRSTUVWXYZ
abcA8defghijklmnopqrstuvwxyz
0123456789/&-+,
"'!@³$%0&&()_-+=|\ {[  }]<,>.:;?/
```

My keyboard layout in Windows is Portuguese Brazilian ABNT.
Can you fix this please?
And a little doubt, where did you find the keyscan/keymap references? I googled it but no luck...

**Comment by ArminJo** [comment]
You can only print plain ASCII with DigiKeyboard.println();
For other character you must use DigiKeyboard.sendKeyStroke().
I fixed the bug in this [repository](https://github.com/ArminJo/DigistumpArduino). You must replace keylayouts.h.
And please close the issue if it works.
