### ISSUE TITLE
Missing character in german layout, but I could fix it

### ISSUE THREAD

**Issue by Cosmoledo** [rsrdesarrollo/DigistumpArduino#3]
When I run the following line

```
DigiKeyboard.println("abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ 1234567890 !\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~");
```

At the german layout (`#define LAYOUT_GERMAN`), it prints:
> abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ 1234567890 !"#$%&'()*+,-./:;<=>?@[\] _ {|}~

Instead of 
> abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ 1234567890 !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

So I am missing two characters at the end of line, ^ and `, both are replaced by spaces.

-----

One of the forked versions did correct both things.

You have to change some indexes in `./DigistumpArduino/blob/master/digistump-avr/libraries/DigisparkKeyboard/keylayouts.h`

Replace line 531
> #define      ASCII_5E      CIRCUMFLEX_BITS + KEY_SPACE      // 94 ^

with

> #define      ASCII_5E      0x35      // 94 ^

Replace line 533
> #define      ASCII_60      GRAVE_ACCENT_BITS + KEY_SPACE      // 96 `

with

> #define      ASCII_60      0x2E | MODIFIERKEY_LEFT_SHIFT      // 96 `

This one fixes it not perfectly because it will generate a ´ and not a `

**Comment by ArminJo** [comment]
> #define ASCII_5E 0x35 // 94 ^
0x35 is a "5" not an ^

**Comment by Cosmoledo** [comment]
You are right, 0x35 is an ascii 5 but here is an other table used. I don't know which but ascii does not matter here.
At least that's my guess, because it works

**Comment by Jeminorch** [comment]
Hey, 
I am kinda of a neewbie to arduino, but had the same problem as Cosmoledo. I am trying out the FRENCH_BELGIAN layout, but a number of characters are not working. My input is:

`#define LAYOUT_FRENCH_BELGIAN`
`#include "DigiKeyboard.h"`
`void setup() {`
`  //empty`
`}`

`void loop() {`
` DigiKeyboard.println("abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ 1234567890 µ£`*]$!#$%&'()*+,- ./:;<=>?@\[]^_`{|}~" ); `
`  for(;;){ /*empty*/ }`
`}`

And the outcome is 
 
`abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ 1234567890  *[$!#$%&'()*+,- ./:;<=>?@][^_ {|} 
`

For now all I need is the backslash `\` actually, so if there is a quick work around in the `./DigistumpArduino/blob/master/digistump-avr/libraries/DigisparkKeyboard/keylayouts.h` that would be wonderful. 

Thanks in advance.

**Comment by ArminJo** [comment]
@Jeminorch 
You see how the backslash is specified in the first line of this issue?
Please google escape character.

**Comment by Jeminorch** [comment]
Ah, so it's not being accepted as a regular key, thanks for the help!

**Comment by ArminJo** [comment]
@Cosmoledo 
I fixed the bug in this [repository](https://github.com/ArminJo/DigistumpArduino). You must replace keylayouts.h.
And please close the issue if it works.

**Comment by Cosmoledo** [comment]
@ArminJo 
I switched to your repository and it works perfectly. All letters are correct and I like the smaller file size. Thank you

@Jeminorch 
My problem is fixed, so I will close this issue. You should also switch to ArminJo Repository. If your problem exists there, you should create a new issue there. For testing you could try this example:

```
#define LAYOUT_FRENCH_BELGIAN
#include "DigiKeyboard.h"

void setup() {
  // first char may not get recognized
  DigiKeyboard.sendKeyStroke(0);
  DigiKeyboard.delay(200);

  DigiKeyboard.print("abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ 1234567890 !\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~");
}

void loop() {
}
```
